# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(419, 320)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.No = QtWidgets.QPushButton(Form)
        self.No.setObjectName("No")
        self.gridLayout_2.addWidget(self.No, 4, 0, 1, 1)
        self.Yes = QtWidgets.QPushButton(Form)
        self.Yes.setObjectName("Yes")
        self.gridLayout_2.addWidget(self.Yes, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.Name = QtWidgets.QLineEdit(Form)
        self.Name.setObjectName("Name")
        self.gridLayout_2.addWidget(self.Name, 0, 1, 1, 1)
        self.SortName = QtWidgets.QLineEdit(Form)
        self.SortName.setObjectName("SortName")
        self.gridLayout_2.addWidget(self.SortName, 1, 1, 1, 1)
        self.Price = QtWidgets.QSpinBox(Form)
        self.Price.setMaximum(99999)
        self.Price.setObjectName("Price")
        self.gridLayout_2.addWidget(self.Price, 3, 1, 1, 1)
        self.Value = QtWidgets.QSpinBox(Form)
        self.Value.setMaximum(999)
        self.Value.setObjectName("Value")
        self.gridLayout_2.addWidget(self.Value, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавление/Изменение кофе"))
        self.label_2.setText(_translate("Form", "Сорт зёрен"))
        self.No.setText(_translate("Form", "Отмена"))
        self.Yes.setText(_translate("Form", "Изменить/Добавить"))
        self.label_3.setText(_translate("Form", "Обьём"))
        self.label.setText(_translate("Form", "Название кофе"))
        self.label_4.setText(_translate("Form", "Цена"))
