# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Table = QtWidgets.QTableWidget(self.centralwidget)
        self.Table.setObjectName("Table")
        self.Table.setColumnCount(5)
        self.Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(4, item)
        self.Table.horizontalHeader().setDefaultSectionSize(155)
        self.Table.horizontalHeader().setMinimumSectionSize(49)
        self.Table.horizontalHeader().setStretchLastSection(True)
        self.Table.verticalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.Table, 1, 0, 1, 1)
        self.AddCoffee = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AddCoffee.setFont(font)
        self.AddCoffee.setObjectName("AddCoffee")
        self.gridLayout_2.addWidget(self.AddCoffee, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Самая Лучшая КофейНЯ!"))
        item = self.Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название"))
        item = self.Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Сорт зёрен"))
        item = self.Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Объём мл."))
        item = self.Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Цена р."))
        self.AddCoffee.setText(_translate("MainWindow", "Добавить кофе"))
